### ISSUE TITLE
Feature request - Support toleration in provider kubernetes

### ISSUE THREAD

**Issue by cakriwut** [loft-sh/devpod-provider-kubernetes#23]
Currently the provider kubernetes allow node selector.  The node selector does not allow selecting node that has been tainted for specific use case or capability, example the more expensive GPU node will be tainted with GPU. 

Request - add support to define toleration in provider kubernetes.

**Comment by pascalbreuninger** [comment]
Hi @cakriwut, you can use the `POD_MANIFEST_TEMPLATE` option to specify taints on your workspace

**Comment by pascalbreuninger** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: does-not-matter
spec:
  containers:
    - name: devpod
  tolerations:
    - key: "example-key"
       operator: "Exists"
       effect: "NoSchedule"
```
