### ISSUE TITLE
Fature Request: Use Pod Template without image

### ISSUE THREAD

**Issue by vanduc2514** [loft-sh/devpod-provider-kubernetes#30]
When I use a pod template without specifing `image` name, the provider refuses to create a workspace because `kubectl` can't deploy a pod with empty image. For example, I use the following template

```
apiVersion: v1
kind: Pod
metadata:
  name: devpod
  labels:
    name: devpod

spec:
  containers:
  - name: devpod
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
```

If I don't use any template, the provider can build the image found in `devcontainer.json` and create a workspace for me. Is there a way for provider to build devcontainer image if the pod template does not have image specify ?  

Workaround for me is to build the devcontainer image first, then push the image to registry and use it for pod template.
