### ISSUE TITLE
Affinity configuration gets accidentally overwritten

### ISSUE THREAD

**Issue by nesta219** [loft-sh/devpod-provider-kubernetes#54]
I think I may have found a bug in the devpod kubernetes provider.  I tried to add a node affinity to my pod yaml and it seems like it gets overwritten here: https://github.com/loft-sh/devpod-provider-kubernetes/blob/65eca07b37d7e0d63ca9bc1c7b7ed936a8f1210f/pkg/kubernetes/run.go#L239-L245

Basically, it seems like it checks for a pod affinity config and if it's not there, it overwrites the entire affinity config with the default preferred by devpod, which deletes any other affinity config that might have been in place

my pod.yaml has this included as part of the spec:
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: NodeType
                operator: In
                values:
                  - devpod
```

but when I launch the devpod, the final value is this:

```
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: devpod.sh/workspace
            operator: In
            values:
            - devpod-buzz-bot-d-dd246
        namespaces:
        - iris
        topologyKey: kubernetes.io/hostname
```

You can still manage node affinity by using the NODE_SELECTOR option for the k8s provider, but now I'm thinking about trying something with anti-affinity (which would fit better with the topology of my cluster- I'd like to tell devpods to avoid certain node groups) and I don't think there's a built-in option for that.

I was able to work around this by setting my pod.yaml up with this affinity config, but it's not really ideal:

```
spec:
  affinity:
    podAffinity:
      RequiredDuringSchedulingIgnoredDuringExecution: []
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: NodeType
                operator: In
                values:
                  - devpod
```

It should be fairly straightforward to adjust the logic to merge in any existing affinity config and layer in the devpod-specific requirements, rather than overwrite them.
