### ISSUE TITLE
Node pending when scheduled with GPU hardware requirements due to node affinity

### ISSUE THREAD

**Issue by allenporter** [loft-sh/devpod-provider-kubernetes#63]
**What happened?**  

Creating a devpod template that specifies resources on limited nodes may mean that a job cannot be scheduled.

I created a kubernetes provider with `requests.nvidia.com/gpu=1` to schedule a job on a machine with a gpu (I only have one node that meets this criteria).  However, the pod never is scheduled and is pending:

```
0/4 nodes are available: 1 node(s) didn't match pod affinity rules, 3 Insufficient nvidia.com/gpu. preemption: 0/4 nodes are available: 1 Preemption is not helpful for scheduling, 3 No preemption victims found for incoming pod.
```

Looking at the affinity rules it depends on another pod `devpod-devpod-default-de-a-d7206` which was scheduled on a machine without a gpu. It seems like the problem is the default job is put on a different arbitrary node

Here is the provider details i've been using:
```
      kubernetes-ml-provider:
        creationTimestamp: "2023-11-27T01:27:32Z"
        initialized: true
        options:
          CLUSTER_ROLE:
            userProvided: true
          CREATE_NAMESPACE:
            userProvided: true
            value: "true"
          DISK_SIZE:
            userProvided: true
            value: 20Gi
          DOCKERLESS_DISABLED:
            userProvided: true
            value: "false"
          DOCKERLESS_IMAGE:
            userProvided: true
          HELPER_IMAGE:
            userProvided: true
          HELPER_RESOURCES:
            userProvided: true
          INACTIVITY_TIMEOUT:
            userProvided: true
          KUBECTL_PATH:
            userProvided: true
            value: kubectl
          KUBERNETES_CONFIG:
            userProvided: true
            value: /Users/allen/Development/k8s-gitops/.env/kubeconfig.yaml
          KUBERNETES_CONTEXT:
            userProvided: true
          KUBERNETES_NAMESPACE:
            userProvided: true
            value: devpod
          KUBERNETES_PULL_SECRETS_ENABLED:
            userProvided: true
            value: "true"
          LABELS:
            userProvided: true
          NODE_SELECTOR:
            userProvided: true
          POD_MANIFEST_TEMPLATE:
            userProvided: true
            value: /Users/allen/Development/devpod-workspaces/manifest/devpod-gpu-template.yaml
          PVC_ACCESS_MODE:
            userProvided: true
          RESOURCES:
            userProvided: true
            value: requests.nvidia.com/gpu=1,limits.memory=10Gi,limits.nvidia.com/gpu=1
          SERVICE_ACCOUNT:
            userProvided: true
          STORAGE_CLASS:
            userProvided: true
        singleMachine: true
```

Contents of `devpod-gpu-template.yaml` with nothing too special:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: devpod-template
  namespace: devpod
  labels:
    devpod/template: "allenporter-gpu"
spec:
  runtimeClassName: nvidia
```

**What did you expect to happen instead?**  

Expect the node to be scheduled on a machine with the required gpu resources.

**Local Environment:**  
- DevPod Version:  0.6.6
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Kubernetes Provider: v1.30.7

**Anything else we need to know?**
